### ISSUE TITLE
Error in object$col$P_VALUE : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by jontheepi** [Kenkleinman/rsatscan#6]
After running: summary(mydata). I receive the following error: Error in object$col$P_VALUE : $ operator is invalid for atomic vectors

When using sample data, I don't receive this error. However, when I am using my own data, I am receiving it.  I am using a dataframes. Variables look to be formatted fine.

**Comment by Kenkleinman** [comment]
I get this error when the function expects a dataframe and I am sending it
(usually) a scalar.  That could happen if (one) of the data sets generates
a failure to converge, for example.
_______________________________________________________
_______________________________________________________
Ken Kleinman, ScD
Associate Professor, Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

Lecturer, Department of Population Medicine
Harvard Medical School

My home page: http://www.kleinman.science
My blog on SAS and R: http://sas-and-r.blogspot.com
My cites on Google Scholar: http://tinyurl.com/KenK-cites
__________________________________________________
** Electronic Mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues. **

**Comment by jontheepi** [comment]
Thanks! Also, I am receiving: Warning message:
running command '"C:/Program Files (x86)/SaTScan/SaTScanBatch" C:/Users/jonathan.gross/Desktop/SAT/Overdose.prm' had status 1  

after calling Overdose = satscan(td, "Overdose")

**Comment by jontheepi** [comment]
Oops, appear to have fixed.

**Comment by jontheepi** [comment]
Oops, appear to have fixed.
